services:
  localstack:
    container_name: ecoscan-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker-reuse
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-central-1}
      - SERVICES=dynamodb,s3,lambda,cloudformation,apigateway,iam,logs,sqs,secretsmanager
      - MAIN_CONTAINER_NAME=ecoscan-localstack
      - LAMBDA_DOCKER_NETWORK=ecoscan-net

    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ecoscan-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  ecoscan-net:
    name: ecoscan-net
    driver: bridge