AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: EcoScan Backend Resources

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  # We'll keep these parameters in case they're referenced elsewhere
  RateLimit:
    Type: Number
    Default: 10
    Description: Number of requests per second allowed (not currently used)

  BurstLimit:
    Type: Number
    Default: 5
    Description: Maximum number of requests allowed in burst (not currently used)

Resources:

  StatusUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: /Users/dmytro.kucherenko/Documents/dev/My/Pet/EcoScan/target/lambda.zip
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - arm64
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          TRASH_BINS_TABLE: !Ref TrashBinsTable
          STATUS_REPORTS_TABLE: !Ref StatusReportsTable
          LOG_LEVEL: INFO
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TrashBinsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref StatusReportsTable

  TrashBinsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-trash-bins
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: binId
          AttributeType: S
      KeySchema:
        - AttributeName: binId
          KeyType: HASH

  StatusReportsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-status-reports
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: binId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: binId
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE

Outputs:
  StatusUpdateFunctionArn:
    Description: ARN of the Status Update Lambda function
    Value: !GetAtt StatusUpdateFunction.Arn
    Export:
      Name: !Sub "${Environment}-EcoScan-StatusUpdateFunctionArn"

  TrashBinsTableName:
    Description: Name of the trash bins table
    Value: !Ref TrashBinsTable

  StatusReportsTableName:
    Description: Name of the status reports table
    Value: !Ref StatusReportsTable