// This file is normally generated by Amplify CLI
// For development purposes, we're creating a manual config file

const awsmobile = {
  "aws_project_region": "eu-central-1",
  "aws_cognito_region": "eu-central-1",
  "aws_user_pools_id": "eu-central-1_XXXXXXXX",
  "aws_user_pools_web_client_id": "your-client-id",
  "oauth": {},
  "aws_cloud_logic_custom": [
    {
      "name": "ecoscanAPI",
      "endpoint": "https://api.example.com",
      "region": "eu-central-1"
    }
  ]
};

export default awsmobile; 