name: Deploy to Dev Environment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            services/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('services/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust and cargo-lambda
        run: |
          if ! command -v cargo-lambda &> /dev/null; then
            cargo install cargo-lambda
          fi

      - name: Install Zig
        run: |
          if ! command -v zig &> /dev/null; then
            wget https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz
            tar xf zig-linux-x86_64-0.11.0.tar.xz
            sudo mv zig-linux-x86_64-0.11.0 /usr/local/zig
            echo "/usr/local/zig" >> $GITHUB_PATH
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to AWS
        run: |
          cd infrastructure/backend
          chmod +x deploy.sh
          ./deploy.sh --environment dev --region eu-central-1