name: Deploy to Dev Environment

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          # Cache both cargo and cargo-lambda
          cache-directories: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            lambda/target
          # Add a key based on the Rust version and the lambda directory
          key: ${{ runner.os }}-cargo-${{ hashFiles('lambda/Cargo.lock') }}
          # Specify the working directory
          working-directory: lambda

      - name: Install Rust and cargo-lambda
        run: |
          if ! command -v cargo-lambda &> /dev/null; then
            cargo install cargo-lambda
          fi

      - name: Install Zig
        run: |
          if ! command -v zig &> /dev/null; then
            wget https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz
            tar xf zig-linux-x86_64-0.11.0.tar.xz
            sudo mv zig-linux-x86_64-0.11.0 /usr/local/zig
            echo "/usr/local/zig" >> $GITHUB_PATH
          fi

      - name: Build Lambda function
        run: |
          cd lambda
          cargo lambda build --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lambda-build
          path: lambda/target/lambda

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: ${{ steps.deploy.outputs.api-url }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: lambda-build
          path: lambda/target/lambda

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to AWS
        id: deploy
        run: |
          cd infrastructure
          chmod +x deploy.sh
          ./deploy.sh dev 